[package]
name = "day3"
version = "0.1.0"
authors = ["Elias Freider <elias.freider@kry.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoclib = { path = "../aoclib" }
regex = "1.4.2"
